### ISSUE TITLE
Crash when Looking up usage of items

### ISSUE THREAD

**Issue by SJ1133** [Chicken-Bones/NotEnoughItems#139]
As above. Whenever 'u" is pressed on an item in the inventory to look up usage the game crashes.
NEI 1.0.3.77 
LOG: http://paste.ee/p/q8AAd

**Comment by polkziggy** [comment]
This may or may not be related. Same symptom though. When looking up the usage of an item, the client laggs and stops responding. Sometimes it comes back. Others , it crashes. Here is a crash report. 

http://pastebin.com/mdTvB9ce

**Comment by IMarvinTPA** [comment]
I got the same issue with the latest version of NEI.
http://pastebin.com/G5iP6LDe
I think there needs to be a test for null such as:

 @SuppressWarnings("unchecked")
public static ItemStack[] extractRecipeItems(Object obj) {
if (obj instanceof ItemStack)
return new ItemStack[]{(ItemStack) obj};
if (obj instanceof ItemStack[])
return (ItemStack[]) obj;
if (obj instanceof List)
return ((List<ItemStack>) obj).toArray(new ItemStack[0]);
if (obj == null) return null;  //Suggested fix.
throw new ClassCastException("not an ItemStack, ItemStack[] or List<ItemStack?");
}


Since it seems all of the other code elsewhere can handle nulls.  It may even be manageable earlier in the tree around codechicken.nei.recipe.ShapelessRecipeHandler.loadUsageRecipes(ShapelessRecipeHandler.java:127)
As it tests for a null result, but it can't get it due to the exception above:

@Override
public void loadUsageRecipes(ItemStack ingredient) {
List<IRecipe> allrecipes = CraftingManager.getInstance().getRecipeList();
for (IRecipe irecipe : allrecipes) {
CachedShapelessRecipe recipe = null;
if (irecipe instanceof ShapelessRecipes)
recipe = shapelessRecipe((ShapelessRecipes) irecipe);
else if (irecipe instanceof ShapelessOreRecipe)
recipe = forgeShapelessRecipe((ShapelessOreRecipe) irecipe);
if (recipe == null)  //This test is never reached.  Need to catch the above exception in this loop and continue.
continue;
if (recipe.contains(recipe.ingredients, ingredient)) {
recipe.setIngredientPermutation(recipe.ingredients, ingredient);
arecipes.add(recipe);
}
}
}

**Comment by mraider94** [comment]
same thing is happening to me, and i also have Magical crops 4.0.0
http://pastebin.com/na9MLv0B

**Comment by Chicken-Bones** [comment]
Call NEI Plugins author

**Comment by IMarvinTPA** [comment]
I have gotten the crash without having NEI Plugins installed.  This is technically some other mod's fault for putting a bad entry into the recipe pool, but it is so random as to who is at fault that it would be so much simpler to have NEI tolerate it rather than having a Crash out of the game level bug.  Sure, throw an alert or error message to the console, but don't crash the game.

http://pastebin.com/ipexvevH

Thank you,

**Comment by IMarvinTPA** [comment]
This bug is still present in 1.7.10-1.0.4.106.

**Comment by Chicken-Bones** [comment]
Fixed c42edf53cf73f8b7603f067b180e5993918f8915 (1.7.10-1.0.4.107)

**Comment by IMarvinTPA** [comment]
It works!  Yay!  Thank you!

IMarv
