### ISSUE TITLE
OpenComputers Incompatibility

### ISSUE THREAD

**Issue by DFrostedWang** [Chicken-Bones/NotEnoughItems#160]
Okay, so I've had this bug with OpenComputers for a while now (months, even from 1.6.4 -> 1.7.10) where sometimes, seemingly at random, I would become [unable to type into a computer.](http://puu.sh/gc6Io/03db75a2e6.mp4) I finally tracked it down to NEI.

If I open a computer I can type into it, however if I close the computer and open my inventory, then close my inventory and go back to the computer, I can no longer type into it. It turns out the issue is that due to [my keyboard layout](http://colemak.com/wiki/images/8/80/Colemak_layout_2.png) and inventory being bound to the F key, NEI search is coming into focus in the computer GUI. This stops any text from being entered into the computer.

**Comment by fnuecke** [comment]
I did some digging, and I think I have a pretty good idea of what's happening now. It's quite the special case. The reason OC fails to capture input in this scenario is that NEI doesn't/can't update its visibility info for OC screens, because that GUI is a simple `GuiScreen`, not a `GuiContainer`.

Therefore the `LayoutManager` apparently keeps the focused element (`getInputFocused`) to what it was in the last GUI. Which, when binding the inventory key to F is the search box. Why does this even matter? I use `LayoutManager.getInputFocused` to check if I should ignore input or not. If there's a better way to do this, please let me know!

I can work around this by simply not checking in the normal screens (in other GUIs this isn't an issue because they are `GuiContainer`s, so the state is updated correctly). I'd still suggest resetting the `inputFocused` field if a GUI is opened that is not a `GuiContainer`, instead of keeping the old state.

**Comment by Chicken-Bones** [comment]
NEI only runs in GuiContainer guis, you probably shouldn't ask NEI for what input element if focused if it's not in control.

**Comment by fnuecke** [comment]
Ah, all right. Then the workaround is actually not a workaround but the way to go. Thanks, feel free to close this then!
