### ISSUE TITLE
Don't know if this is an issue with NEI but I think it is.

### ISSUE THREAD

**Issue by fewewq** [Chicken-Bones/NotEnoughItems#166]
When you have a full inventory of items and you add another item to your inventory using nei and you don't have enough slots you crash. Here is the link to crash report http://paste.ee/p/r8pQW

**Comment by da3dsoul** [comment]
Recommend renaming this to "Crash when giving an item whilest inventory is full" or akin. I can verify it happens on all mode that allows hacking in items (so not recipe, obviously).

**Comment by Chicken-Bones** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/issues/153

**Comment by da3dsoul** [comment]
Thank you chicken bones. I hadn't realized there was a fix.

**Comment by decryptedchaos** [comment]
This bug is driving me absolutely crazy,  its still happening on FTB 1.7.10,  i even downloaded the latest version from the site,  bug is still present,  i play a lot of creative  when trying new designs and such,  and this occurs at least 15 times a day,  if it wasn't for the fact of needing NEI i would just disable it,  unfortunately i depend on it too much. i tried disabling it but the built in (vanilla) search for items is so dreadfully laggy  to the point of being unbearable, but this bug is running a close race with it crashing my client every 30 minutes or so.    i see a fix was committed,  but apparently these fixes are not in the latest 1.7.10 version.  can someone please fix this for 1.7.10,  or point me to a fixed jar that i may have overlooked
