### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [Chicken-Bones/NotEnoughItems#306]
I get the Following crash using HQM Book and try to looking for a recipe.

Test case:
Join a game.
Don't open NEI inventory.
Open any quest in the HQM Quest book.
Try to open any recipe the HQM Quest book. with R button (this should trigger NEI opening).
Game will crash.

https://gist.github.com/Dream-Master/25b4041c4885fde37d8f#file-nei

http://openeye.openmods.info/crashes/9a8f82d382cb416f77ca038e853cfbac

**Comment by Blue64** [comment]
I would like to point out a few problems with this crash:
* Optifine is installed
  * not supported by 2 of your other mods
  * Closed Source Mod
* it's a kCauldron Server
  * a lot of mods are shying away (or fleeing) support for kCauldron Servers because they change some behavior in the way MineCraft actually runs (I don't recall what specifically it changes)

Have you been able to reproduce this in Single Player, or only on the Server? If it's only on the Server, you'd need to contact the kCauldron people about it.

**Comment by Chicken-Bones** [comment]
`at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.setIngredients(NEIBloodOrbShapedHandler.java:47)`
Report to WayofTime nei plugin dev

**Comment by Dream-Master** [comment]
I did

https://github.com/WayofTime/BloodMagic/issues/507

**Comment by Blue64** [comment]
@Chicken-Bones he did, still no response from them, and I don't think either of us knew if you had provided that support, or if they had provided it. thank you for your (eventual) response.
